### ISSUE TITLE
Diamond fragments can't be crafted into diamonds (1.20 Forge)

### ISSUE THREAD

**Issue by tigermozze** [Lemon-Juiced/ScalarUtils5AgricultureAddon#1]
I have encountered a bug/issue. The title is the issue, however a diamond can be converted into 9 diamond fragments.

**Comment by TigerADPC** [comment]
FYI: the title is diamonds fragments cannot be crafted into diamonds*

**Comment by Lemon-Juiced** [comment]
Currently seeing this as im leaving work. I'll send out a patch when I get home. I believe it worked in 1.19 so I must've broke something during the port.

**Comment by Lemon-Juiced** [comment]
Just to save me time if possible is this an issue in both 1.20 or 1.20.1 if you know?

**Comment by Lemon-Juiced** [comment]
This was fixed in the latest Lemon Core build, it was that mod's problem not this one. Granted that mod is this mod's backbone, but the fix needed to be done in that mod not here.

**Comment by Lemon-Juiced** [comment]
Thank you for your contribution in catching the issue.

**Comment by tigermozze** [comment]
> This was fixed in the latest Lemon Core build, it was that mod's problem not this one. Granted that mod is this mod's backbone, but the fix needed to be done in that mod not here.

Can I ask for a 1.20 Forge version or is that uneccessary/too much?
Also the version I played where this issue existed was 1.20 Forge just to be precise.

**Comment by Lemon-Juiced** [comment]
I wasn't planning to backport to earlier versions with the adoption of 1.20.1 but will this time when I get home.

**Comment by Lemon-Juiced** [comment]
Its fixed in the newest version, it's still uploading to CurseForge, enjoy it Mr. TigerADPC
